In [3]:
import numpy as np

# 随机生成数组
a = np.random.rand(4, 4)
a

array([[ 0.61390435,  0.16940091,  0.50286746,  0.72404753],
       [ 0.74291141,  0.3233356 ,  0.77395247,  0.07985978],
       [ 0.38582407,  0.94037643,  0.10466757,  0.82924723],
       [ 0.30789176,  0.43289267,  0.8938481 ,  0.50500711]])

In [6]:
# 数组转化为矩阵
randMat = np.mat(a)
randMat

matrix([[ 0.61390435,  0.16940091,  0.50286746,  0.72404753],
        [ 0.74291141,  0.3233356 ,  0.77395247,  0.07985978],
        [ 0.38582407,  0.94037643,  0.10466757,  0.82924723],
        [ 0.30789176,  0.43289267,  0.8938481 ,  0.50500711]])

In [9]:
# 求逆
inv = randMat.I
inv

matrix([[ 0.78739972,  1.26882864,  0.13904985, -1.55789867],
        [-1.39140733,  0.5247943 ,  1.03841716,  0.20679021],
        [-0.30349088, -0.02309348, -0.57097904,  1.37635459],
        [ 1.24982575, -1.18255648,  0.03570851,  0.31661786]])

In [10]:
randMat * inv

matrix([[  1.00000000e+00,  -2.22044605e-16,   0.00000000e+00,
           5.55111512e-17],
        [ -5.55111512e-17,   1.00000000e+00,   0.00000000e+00,
           6.93889390e-17],
        [ -5.55111512e-17,  -5.55111512e-17,   1.00000000e+00,
          -5.55111512e-17],
        [ -6.93889390e-18,  -5.55111512e-17,  -1.11022302e-16,
           1.00000000e+00]])

In [13]:
myEye = randMat * inv
myEye - np.eye(4)

matrix([[  0.00000000e+00,  -2.22044605e-16,   0.00000000e+00,
           5.55111512e-17],
        [ -5.55111512e-17,  -2.22044605e-16,   0.00000000e+00,
           6.93889390e-17],
        [ -5.55111512e-17,  -5.55111512e-17,   0.00000000e+00,
          -5.55111512e-17],
        [ -6.93889390e-18,  -5.55111512e-17,  -1.11022302e-16,
           0.00000000e+00]])